# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: v2
appVersion: 0.10.0
description: The core chart for Gitpod
name: gitpod
version: 1.0.40
kubeVersion: ">=1.19.0-0"
icon: https://www.gitpod.io/favicon192.png

dependencies:
- name: docker-registry
  version: 1.11.0
  repository: https://helm.twun.io
  condition: docker-registry.enabled
- name: minio
  version: 8.0.10
  repository: https://helm.min.io/
  condition: minio.enabled
- name: mysql
  version: 8.6.2
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled
- name: rabbitmq
  version: 8.16.0
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled
