# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $certManager := (index .Values "cert-manager") }}
{{ if (index .Values "docker-registry" "enabled") }}
{{- $regName := include "gitpod.builtinRegistry.name" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: builtin-registry-certs
spec:
  # ~6 months
  duration: 4380h
  secretName: builtin-registry-certs
  dnsNames: {{ ( list $regName ) | toJson }}
  issuerRef:
    name: {{ $certManager.ca.issuerName }}
    kind: Issuer
    group: cert-manager.io
{{- end }}
---
# SSL certificate for internal registry
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitpod-registry
spec:
  # ~6 months
  duration: 4380h
  secretName: gitpod-registry-cert
  dnsNames:
    - {{ (printf "reg.%s" (.Values.components.registryFacade.hostname | default .Values.hostname)) | quote }}
  issuerRef:
    name: {{ $certManager.ca.issuerName }}
    kind: Issuer
    group: cert-manager.io
