# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $certManager := (index .Values "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gitpod-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certManager.ca.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ $certManager.ca.issuerName }}
  secretName: {{ $certManager.ca.secretName }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: gitpod-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $certManager.ca.issuerName }}
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ $certManager.ca.secretName }}
