# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: v1
kind: ConfigMap
metadata:
  name: update-ca-certificates
data:
  setup.sh: |
    echo "$GITPOD_CA_CERT" > /usr/local/share/ca-certificates/gitpod-ca.crt && mkdir -p /etc/containerd/certs.d/reg.{{ .Values.hostname }} && echo "$GITPOD_CA_CERT" > /etc/containerd/certs.d/{{- (printf "reg.%s:%v" (.Values.components.registryFacade.hostname | default .Values.hostname) .Values.components.registryFacade.ports.registry.servicePort) -}}/ca.crt && update-ca-certificates
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-ca-certificates
  labels:
    app: update-ca-certificates
spec:
  selector:
    matchLabels:
      app: update-ca-certificates
  template:
    metadata:
      labels:
        app: update-ca-certificates
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: update-ca-certificates
        command: ["nsenter"]
        args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(SETUP_SCRIPT)"]
        image: ubuntu:20.04
        env:
        - name: GITPOD_CA_CERT
          valueFrom:
            secretKeyRef:
              name: builtin-registry-certs
              key: ca.crt
        - name: SETUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              name: update-ca-certificates
              key: setup.sh
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.5
