name: Helm

on:
  push:
    branches:
      - main

jobs:

  changes:
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'aledbf/gitpod-chart-cleanup')
    outputs:
      chart: ${{ steps.filter.outputs.chart }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            chart:
              - 'chart/Chart.yaml'
              - 'chart/**/*'

  chart:
    name: Release Chart
    runs-on: ubuntu-latest
    needs:
      - changes
    if: |
      (github.repository == 'aledbf/gitpod-chart-cleanup') &&
      (needs.changes.outputs.chart == 'true')

    steps:

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0

      - name: Setup
        shell: bash
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-chart-{{ .Version }}"
        with:
          charts_dir: chart
